### ISSUE TITLE
Display error notification when not compiled

### ISSUE THREAD

**Issue by OAyomide** [wasm-lab/wasm-playground#1]
For people that just clone/fork the repo without having the EMSCRIPTEN SDK installed on their machine, there should be a way to notify them that there is an issue compiling the file.

Things I noticed:
* The devTools: Error 500 is actually returned when the button is clicked.
* In ```server/controller/compile.js```, I could see ```process.env.EMSCRIPTEN_BINARY``` on line 27.

The apparent solution is rendering an alert dialog when the server returns 500 (with the appropriate message). Anybody who knows Vue should knock themselves out.

@orobogenius

**Comment by orobogenius** [comment]
`process.env.EMSCRIPTEN_BINARY` should point to the location of emscripten compiler binary `emcc`, relative to your home directory. An example is given in the `.env.example` configuration file.

**Comment by OAyomide** [comment]
Yeah. I later on saw that. But then the issue still stands. They have to know they cant compile without installing that.

Also I think we have to document that. Right now, unless you look into the code, you wont know what you are doing wrong. You'll just see that you cant compile

What do you think?

**Comment by orobogenius** [comment]
Alright, I'll update the README with instructions on how to install emscripten and also changing the EMSCRIPTEN_BINARY key to point to the binary's location. Better still, maybe we eliminate the need to manually specify the location and just source the binary path on the terminal so we can just call `emcc` directly.

**Comment by OAyomide** [comment]
Sounds like a plan!

:+1:  perhaps you'll make a commit for that?

**Comment by OAyomide** [comment]
Fixed via a0833304a281b21c5ba4be6dc15a325cba56d7a1
